### ISSUE TITLE
Support for multiple Jira instances

### ISSUE THREAD

**Issue by scooper4711** [srz2/obsidian-jira-linker#1]
My organization uses multiple JIRA instances (don’t ask. We’re a big company. Left hand, meet right).

Lucky for us, the prefixes don’t overlap (at least not for the projects I care about).

I’d like to be able to use your plugin to link to either instance. I can tell by looking at a ticket which instance it belongs to. I would be happy having two different commands to link to two different instances, or ideally I configure which ticket patterns go to which JIRA instance (maybe even having a default instance if nothing matches).

Thanks! Very handy plugin!

**Comment by srz2** [comment]
@scooper4711 thank you for your suggestion. It was a fun thing to implement. Please let me know if you have any other suggestions!

The new feature is now live!
