### ISSUE TITLE
Disable newline after link creation

### ISSUE THREAD

**Issue by kubeliv** [srz2/obsidian-jira-linker#3]
Hi there,

Firstly, kudos on the excellent work with this plugin—it's been incredibly useful. I have a minor suggestion regarding its functionality. Would it be possible to include an option to disable the automatic insertion of a new line after creating a link?

Personally, I often take notes in bullet point format, and it becomes tedious to manually remove the extra line when I want to add details after inserting a link.

**Comment by srz2** [comment]
Hi, thanks for the complement. Yeah, this was always a minor issue I noticed that bugged me too, I'll have a look to see how hard it is.

thanks for the suggestion and I'm glad you like the plugin

**Comment by srz2** [comment]
@kubeliv, thank you for your suggestion. Please let me know if you have any other suggestions!

The new feature is now live!
