### ISSUE TITLE
[Feature Request] Don't create a folder for every issue/note

### ISSUE THREAD

**Issue by Kageetai** [srz2/obsidian-jira-linker#5]
Hello,

thanks for this well thought-out plugin and it works mostly great. Just one thing I would like slightly different:
Would it be possible to not create a new folder for every local issue? I just want a simple note for every issue, not necessarily a new folder.

Thanks in advance

**Comment by srz2** [comment]
Thank you for your request @Kageetai 
I completed and released a new version of the plugin, please refer to #6 for details

**Comment by Kageetai** [comment]
Awesome, thanks for that quick fix. I was also wondering then, whether that "Local Issue Main File Name" could be optional then. As I don't need a folder for the issue, I don't need any suffix either. Thanks 🙏

**Comment by srz2** [comment]
I agree with you. I thought about it when I first made the change and didn't change it. But making it optional is a better flow.

Thanks for the suggestion @Kageetai . It is now live for [version 1.1.3](https://github.com/srz2/obsidian-jira-linker/releases/tag/1.1.3)

**Comment by Kageetai** [comment]
That's awesome, thanks for the quick changes.
